
server.port=8080

#direccion mysqllocal
spring.datasource.url=jdbc:mysql://localhost:3306/citas_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# Tu usuario de MySQL Workbench (por defecto suele ser root)
spring.datasource.username=root

# La contraseña que le pusiste a tu MySQL cuando lo instalaste
spring.datasource.password=

# El driver que maneja la conexión
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# "Revisa las clases de Java y crea o actualiza las tablas en MySQL automáticamente".
spring.jpa.hibernate.ddl-auto=update

# El dialecto le dice a Hibernate cómo hablar el "dialecto" específico de MySQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Subimos a 35 para aguantar la autogestión futura y las ráfagas de las cajas sin esfuerzo
spring.datasource.hikari.maximum-pool-size=35

# Mantenemos 10 conexiones siempre vivas y listas para responder al milisegundo
spring.datasource.hikari.minimum-idle=10

# Tiempo máximo de espera para obtener una conexión (Reducido a 15 seg).
# Si el sistema tarda más de 15 segundos en responder, es mejor alertar que hacer esperar al cliente de autogestión eternamente
spring.datasource.hikari.connection-timeout=15000

# Bajamos el tiempo ocioso a 5 minutos para liberar conexiones rápido si un vendedor se distrae
spring.datasource.hikari.idle-timeout=300000

# Vida máxima de la conexión (30 minutos)
spring.datasource.hikari.max-lifetime=1800000

#para que escuche en local
server.address=0.0.0.0

#para las fotos
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB
# Indicarle a Spring que está detrás de un proxy (Cloudflare)
server.forward-headers-strategy=framework
